# Generated by Django 4.1.5 on 2023-01-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0003_alter_donation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Fundacja'), (2, 'Organizacja pozarządowa'), (3, 'zbiórka lokalna')]),
        ),
    ]
